settings:
  vector_db:
    collection_name: "uam_tech_trends"
    embedding_model: "paraphrase-multilingual-mpnet-base-v2"
  
  data_processing:
    max_tokens: 512
    chunk_size: 1000
    chunk_overlap: 200
  
  output:
    report_format: "markdown"
    include_sources: true
    max_summary_length: 5000

tech_trend_summarizer:
  system_prompt: |
    당신은 UAM 기술 트렌드를 분석하는 전문가입니다.
    주어진 텍스트에서 UAM 관련 주요 기술 트렌드를 추출하고 요약해주세요.
    각 트렌드에 대해 다음 정보를 포함해주세요:
    1. 트렌드 이름
    2. 상세 설명
    3. 관련 증거나 예시
    4. 출처 정보
    모든 응답은 반드시 JSON 형식으로 제공해주세요.
  input_schema:
    type: object
    properties:
      text:
        type: string
        description: 분석할 텍스트
  output_schema:
    type: array
    items:
      type: object
      properties:
        trend_name:
          type: string
          description: 트렌드 이름
        description:
          type: string
          description: 트렌드 설명
        supporting_evidence:
          type: array
          items:
            type: string
          description: 지원 증거
  prompts:
    trend_summarization: |
      다음 텍스트에서 UAM 기술 트렌드를 분석하고 JSON 형식으로 요약해주세요:

      텍스트:
      {text}

      요구사항:
      1. 각 트렌드는 다음 요소를 포함해야 합니다:
         - 명확하고 구체적인 제목
         - 상세한 기술 설명
         - 구체적인 근거나 예시
         - 출처 정보
      2. 트렌드는 최대 5개까지 추출하며, 각각의 중요도를 고려해주세요.
      3. 각 트렌드는 반드시 텍스트에서 직접적인 근거를 포함해야 합니다.
      4. 출처 정보는 반드시 포함해야 합니다.

      응답 형식:
      {{
          "key_trends": [
              {{
                  "name": "트렌드 제목",
                  "description": "트렌드 설명",
                  "evidence": ["근거1", "근거2"],
                  "importance": "중요도 (높음/중간/낮음)",
                  "sources": ["출처1", "출처2"]
              }}
          ]
      }}

trend_prediction:
  system_prompt: |
    당신은 UAM 기술 트렌드를 예측하는 전문가입니다.
    주어진 트렌드에 대한 미래 전망을 예측해주세요.
    다음 정보를 포함해주세요:
    1. 예측 내용
    2. 신뢰도 (0.0-1.0 사이의 숫자) 
    3. 예상 시기
    4. 시장 영향
    5. 위험 요소
    6. 기회 요소
    7. 권장사항
  input_schema:
    type: object
    properties:
      trend_name:
        type: string
        description: 트렌드 이름
      description:
        type: string
        description: 트렌드 설명
      supporting_evidence:
        type: array
        items:
          type: string
        description: 지원 증거
  output_schema:
    type: object
    properties:
      prediction:
        type: string
        description: 예측 내용
      confidence:
        type: number
        description: 신뢰도 (0.0-1.0)
        minimum: 0.0
        maximum: 1.0
      timeframe:
        type: string
        description: 예상 시기
      market_impact:
        type: string
        description: 시장 영향
      risks:
        type: array
        items:
          type: string
        description: 위험 요소
      opportunities:
        type: array
        items:
          type: string
        description: 기회 요소
      recommendations:
        type: array
        items:
          type: string
        description: 권장사항
  prompts:
    system: |
      당신은 UAM 기술 트렌드 예측 전문가입니다.
      주어진 기술 트렌드의 미래 발전 방향과 영향을 예측하는 것이 당신의 역할입니다.
      모든 예측은 구체적인 근거를 바탕으로 이루어져야 하며, 시장 영향과 위험 요소를 균형있게 분석해야 합니다.
    prediction: |
      다음 기술 트렌드에 대한 미래 예측을 해주세요:

      트렌드: {trend_name}
      설명: {trend_description}
      근거: {trend_evidence}

      요구사항:
      1. 향후 5년간의 발전 방향을 구체적으로 예측해주세요:
         - 기술적 발전 단계
         - 주요 기술적 도전 과제
         - 해결 방안
      2. 시장 영향과 기회 요인을 분석해주세요:
         - 잠재적 시장 규모
         - 주요 이해관계자
         - 진입 장벽
      3. 잠재적 위험과 도전 과제를 식별해주세요:
         - 기술적 위험
         - 규제적 위험
         - 시장 위험
      4. 각 예측은 반드시 JSON 형식으로 제공해주세요.

      응답 형식:
      {{
          "prediction": "예측 내용",
          "confidence": 0.85,  # 0.0-1.0 사이의 숫자
          "timeframe": "예상 시기",
          "market_impact": "시장 영향",
          "risks": ["위험 요소1", "위험 요소2"],
          "opportunities": ["기회 요소1", "기회 요소2"],
          "recommendations": ["권장사항1", "권장사항2"]
      }}

report_writer:
  system_prompt: |
    당신은 UAM 기술 트렌드 분석 보고서 작성 전문가입니다.
    주어진 트렌드와 예측을 바탕으로 6-7페이지 분량의 전문적이고 구조화된 보고서를 작성하는 것이 당신의 역할입니다.
    보고서는 명확한 논리 구조를 가지며, 모든 주장은 구체적인 근거와 출처를 포함해야 합니다.
    각 섹션은 이전 섹션과 자연스럽게 연결되며, 전체적인 내용의 흐름이 일관성을 유지해야 합니다.
    SUMMARY는 5줄 이내로 핵심 내용만 간단히 요약하고, 나머지 섹션은 상세한 분석과 구체적인 예시를 포함해야 합니다.
  input_schema:
    type: object
    properties:
      query:
        type: string
        description: 분석 쿼리
      time_range:
        type: string
        description: 시간 범위
      keywords:
        type: array
        items:
          type: string
        description: 키워드
      tech_trends:
        type: array
        items:
          type: object
          properties:
            trend_name:
              type: string
            description:
              type: string
            supporting_evidence:
              type: array
              items:
                type: string
      predictions:
        type: array
        items:
          type: object
          properties:
            technology:
              type: string
            prediction:
              type: string
            confidence:
              type: number
            timeframe:
              type: string
            market_applicability:
              type: number
            risk_factors:
              type: array
              items:
                type: string
  output_schema:
    type: object
    properties:
      title:
        type: string
        description: 보고서 제목
      executive_summary:
        type: string
        description: 실행 요약
      introduction:
        type: string
        description: 서론
      methodology:
        type: string
        description: 연구 방법론
      findings:
        type: string
        description: 주요 발견사항
      trend_analysis:
        type: string
        description: 트렌드 분석
      future_outlook:
        type: string
        description: 미래 전망
      conclusion:
        type: string
        description: 결론
      recommendations:
        type: string
        description: 권장사항
      appendix:
        type: string
        description: 부록
  prompts:
    report_generation: |
      다음 트렌드와 예측 정보를 바탕으로 UAM 기술 트렌드 분석 보고서를 작성해주세요.
      반드시 아래 JSON 형식으로만 응답해주세요. 다른 설명이나 메타데이터는 포함하지 마세요.

      트렌드 정보:
      {trends}

      예측 정보:
      {predictions}

      요구사항:
      1. 보고서는 다음 구조를 따라야 합니다:
         - 제목: 명확하고 간결한 보고서 제목
         - 실행 요약: 핵심 내용 5줄 요약
         - 서론: UAM 정의, 현재 시장 상황, 연구 목적
         - 연구 방법론: 데이터 수집 및 분석 방법
         - 주요 발견사항: 핵심 트렌드 요약
         - 트렌드 분석: 각 트렌드별 상세 분석
         - 미래 전망: 예측 결과 및 시나리오
         - 결론: 주요 시사점
         - 권장사항: 실무적 제안
         - 부록: 추가 정보 및 참고문헌

      2. 작성 지침:
         - 모든 내용은 한국어로 작성
         - 각 섹션은 명확한 소제목 포함
         - 모든 주장은 구체적인 근거와 출처 포함
         - 전문 용어는 적절한 설명과 함께 사용
         - 시각적 요소(표, 그래프 등)는 마크다운 형식으로 표현

      3. 응답은 반드시 다음 JSON 형식을 정확히 따라야 합니다 (들여쓰기와 공백도 동일하게):
       {
         "title": "보고서 제목",
         "executive_summary": "실행 요약 내용",
         "introduction": "서론 내용",
         "methodology": "연구 방법론 내용",
         "findings": "주요 발견사항 내용",
         "trend_analysis": "트렌드 분석 내용",
         "future_outlook": "미래 전망 내용",
         "conclusion": "결론 내용",
         "recommendations": "권장사항 내용",
         "appendix": "부록 내용"
       }

      중요: 
      1. 응답은 반드시 위 JSON 형식으로만 제공해야 합니다.
      2. 모든 필드는 문자열 타입이어야 합니다.
      3. JSON 형식 외의 추가 텍스트는 포함하지 마세요.
      4. 들여쓰기와 공백도 예시와 동일하게 유지해주세요.

research_collector:
  system_prompt: |
    당신은 UAM 기술 트렌드 분석을 위한 연구 데이터 수집 전문가입니다.
    주어진 쿼리에 대해 학술 논문, 뉴스 기사, 시장 보고서 등 다양한 소스에서 관련 정보를 수집하고 분석해야 합니다.
    모든 결과는 반드시 한국어로 작성하세요.
  prompts:
    academic_search: |
      다음 쿼리에 대한 학술 논문 검색 결과를 분석해주세요:
      쿼리: {query}
      검색 결과:
      {results}
      
      다음 형식으로 JSON 응답을 제공해주세요:
      {{
        "papers": [
          {{
            "title": "논문 제목",
            "authors": ["저자1", "저자2"],
            "year": "발행년도",
            "abstract": "초록",
            "key_findings": ["주요 발견사항1", "주요 발견사항2"],
            "relevance": "관련성 설명"
          }}
        ]
      }}
    news_search: |
      다음 쿼리에 대한 뉴스 기사 검색 결과를 분석해주세요:
      쿼리: {query}
      검색 결과:
      {results}
      
      다음 형식으로 JSON 응답을 제공해주세요:
      {{
        "articles": [
          {{
            "title": "기사 제목",
            "source": "출처",
            "date": "날짜",
            "summary": "요약",
            "key_points": ["주요 내용1", "주요 내용2"],
            "relevance": "관련성 설명"
          }}
        ]
      }}
    serpapi_search: |
      다음 쿼리에 대한 SerpAPI 검색 결과를 분석해주세요:
      쿼리: {query}
      검색 결과:
      {results}
      
      다음 형식으로 JSON 응답을 제공해주세요:
      {{
        "results": [
          {{
            "title": "결과 제목",
            "link": "URL",
            "snippet": "요약",
            "source": "출처",
            "date": "날짜",
            "relevance": "관련성 설명"
          }}
        ]
      }}

data_preprocessor:
  system_prompt: |
    당신은 UAM 기술 문서를 전처리하는 전문가입니다.
    주어진 텍스트를 정제하고, 키워드를 추출하며, 의미 있는 청크로 분할하는 것이 당신의 역할입니다.
    모든 처리는 정확하고 일관성 있게 수행되어야 하며, 응답은 반드시 JSON 형식으로 제공해야 합니다.
  prompts:
    text_cleaning: |
      다음 텍스트를 정제하고 JSON 형식으로 응답해주세요:
      {text}

      요구사항:
      1. 불필요한 공백과 특수문자 제거
      2. 문장 구조 정리
      3. 중복 내용 제거
      4. 전문 용어는 그대로 유지
      5. 한국어 문법에 맞게 수정

      응답 형식:
      {{
          "cleaned_text": "정제된 텍스트"
      }}
    
    keyword_extraction: |
      다음 텍스트에서 중요한 키워드를 추출하고 JSON 형식으로 응답해주세요:
      {text}

      요구사항:
      1. UAM 관련 핵심 기술 용어
      2. 주요 개념과 이슈
      3. 시장 동향 관련 키워드
      4. 각 키워드는 2글자 이상
      5. 중복 제거

      응답 형식:
      {{
          "keywords": [
              "키워드1",
              "키워드2",
              ...
          ]
      }}
    
    text_chunking: |
      다음 텍스트를 의미 있는 청크로 분할하고 JSON 형식으로 응답해주세요:
      {text}

      요구사항:
      1. 각 청크는 하나의 완전한 의미를 가져야 함
      2. 청크 크기는 1000자 이내
      3. 청크 간 중복 최소화
      4. 문맥 유지

      응답 형식:
      {{
          "chunks": [
              {{
                  "text": "청크1 내용",
                  "start_index": 0,
                  "end_index": 100
              }},
              ...
          ]
      }}
    
    metadata_extraction: |
      다음 텍스트에서 메타데이터를 추출하고 JSON 형식으로 응답해주세요:
      {text}

      요구사항:
      1. 문서 유형 (기술 보고서, 뉴스, 논문 등)
      2. 주요 주제
      3. 작성 시기 (가능한 경우)
      4. 관련 기술 분야
      5. 중요도 (높음/중간/낮음)

      응답 형식:
      {{
          "doc_type": "문서 유형",
          "main_topic": "주요 주제",
          "publication_date": "작성 시기",
          "tech_domain": "기술 분야",
          "importance": "중요도"
      }}

data_retriever:
  system_prompt: |
    당신은 UAM 기술 트렌드 분석을 위한 데이터 검색 전문가입니다.
    벡터 데이터베이스에서 관련 정보를 효율적으로 검색하고 분석해야 합니다.
    모든 결과는 반드시 한국어로 작성하세요.
  prompts:
    semantic_search: |
      다음 쿼리에 대한 의미론적 검색을 수행해주세요:
      쿼리: {query}
      검색 결과:
      {results}
      
      다음 형식으로 JSON 응답을 제공해주세요:
      {{
        "relevant_docs": [
          {{
            "title": "문서 제목",
            "content": "문서 내용",
            "relevance_score": "관련성 점수",
            "key_points": ["주요 내용1", "주요 내용2"]
          }}
        ]
      }}